name: Hello Workflow

on:
  push:
    branches: [main]

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world message
        run: echo "Hello World!"

      - name: Show current date
        run: date

      - name: Show current directory content
        run: ls -alh
